apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mentor-bot.fullname" . }}-secrets
  labels:
    {{- include "mentor-bot.labels" . | nindent 4 }}
type: Opaque
data:
  COMMON_BOT_TOKEN: {{ .Values.secrets.common.botToken | b64enc }}
  COMMON_ENCRYPTION_KEY: {{ .Values.secrets.common.encryptionKey | b64enc }}
  COMMON_ADMINS: {{ .Values.secrets.common.admins | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | b64enc }}
  REDIS_PASSWORD: {{ .Values.secrets.redis.password | b64enc }}
  PROVIDER_TOKEN: {{ .Values.secrets.provider.token | b64enc }}
  OPENAI_API_KEY: {{ .Values.secrets.openai.apiKey | b64enc }}