apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mentor-bot

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - qdrant.yaml
  - bot.yaml

commonLabels:
  app.kubernetes.io/name: mentor-bot
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: telegram-bot

images:
  - name: ghcr.io/YOUR_USERNAME/mentor-bot
    newTag: latest