apiVersion: v1
kind: Secret
metadata:
  name: mentor-bot-secrets
  namespace: mentor-bot
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # To encode: echo -n "your-value" | base64
  COMMON_BOT_TOKEN: ""  # Replace with base64 encoded bot token
  COMMON_ENCRYPTION_KEY: ""  # Replace with base64 encoded encryption key
  COMMON_ADMINS: ""  # Replace with base64 encoded JSON array of admin IDs
  POSTGRES_PASSWORD: ""  # Replace with base64 encoded postgres password
  REDIS_PASSWORD: ""  # Replace with base64 encoded redis password
  PROVIDER_TOKEN: ""  # Replace with base64 encoded provider token
  OPENAI_API_KEY: ""  # Replace with base64 encoded OpenAI API key