"""bool fields user

Revision ID: 3f3d917334a5
Revises: 56ad3d4e4a3a
Create Date: 2025-08-05 18:43:22.643387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f3d917334a5'
down_revision: Union[str, None] = '56ad3d4e4a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_sub', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_reg', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_reg')
    op.drop_column('users', 'is_sub')
    # ### end Alembic commands ###
