"""init

Revision ID: 415996f573f2
Revises: 
Create Date: 2025-07-23 01:29:33.472828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415996f573f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('brief_background', sa.String(length=512), nullable=True),
    sa.Column('goal', sa.String(length=512), nullable=True),
    sa.Column('telegram_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentors',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mentor_age', sa.Integer(), nullable=False),
    sa.Column('background', sa.String(length=256), nullable=False),
    sa.Column('recent_events', sa.String(length=1024), nullable=False),
    sa.Column('personality_style', sa.String(length=256), nullable=False),
    sa.Column('greeting', sa.String(length=256), nullable=False),
    sa.Column('sys_prompt_summary', sa.String(length=1024), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentors')
    op.drop_table('users')
    # ### end Alembic commands ###
