"""conversation data bigger

Revision ID: 56ad3d4e4a3a
Revises: c7931a6f93bc
Create Date: 2025-07-23 16:40:37.664288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ad3d4e4a3a'
down_revision: Union[str, None] = 'c7931a6f93bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_messages', 'content',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=4096),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_messages', 'content',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
